# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "hugoline"
license = "MIT"
licenselink = "https://github.com/adamnieto/hugoline/blob/main/LICENSE"
description = "A portfolio theme that uses Preline UI and Tailwind CSS."
homepage = "https://github.com/adamnieto/hugoline"
tags = ["Hugo", "Preline UI", "Tailwind CSS", "theme", "portfolio"]
features = []
min_version = "0.1.0"

[author]
  name = "Adam Nieto"
  homepage = "https://github.com/adamnieto/"


[module]
  [module.hugoVersion]
    extended = false
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"