theme = "hugoline"
languageCode = "en-us"
baseurl = "http://example.com/"
title = "John Doe"

copyright = "© 2024, John Doe"

[params]
  name = "John Doe"
  email = "john.doe@example.com"
  tagline = "a software engineer who loves to innovate."
  description = "A new theme for Hugo, build with Tailwindcss and Preline UI."
  favicon = "favicon.ico"

  linkedin_url = "https://example.com"
  github_url = "https://example.com"

  mode = "development"

  logo = "/logo.png"    
  profile_logo = "/profile.png"

  [[param.meta]]
    favicon = true

[module]
  [[module.mounts]]
    source = "node_modules/preline/preline.js"
    target = "assets/js/preline.js"  

# syntax highlight settings
[markup]
  [markup.highlight]
    style = 'catppuccin-latte'  
    lineNos = true
    lineNumbersInTable = false

